/* eslint-disable no-shadow */

export enum SummaryTypes {
    SUMMARY_CREATE_SUCCESS = 'SUMMARY_CREATE_SUCCESS',
    SUMMARY_CREATE_REQUEST = 'SUMMARY_CREATE_REQUEST',
    SUMMARY_CREATE_FAILURE = 'SUMMARY_CREATE_FAILURE',
    SUMMARY_EDIT_SUCCESS = 'SUMMARY_EDIT_SUCCESS',
    SUMMARY_EDIT_REQUEST = 'SUMMARY_EDIT_REQUEST',
    SUMMARY_EDIT_FAILURE = 'SUMMARY_EDIT_FAILURE',
    SUMMARIES_UPDATE_REQUEST = 'SUMMARIES_UPDATE_REQUEST',
    SUMMARIES_UPDATE_FAILURE = 'SUMMARIES_UPDATE_FAILURE',
    SUMMARIES_UPDATE_SUCCESS = 'SUMMARIES_UPDATE_SUCCESS',
}
