/* eslint-disable no-shadow */

export enum SummaryTypes {
    SUMMARY_UPDATE_SUCCESS = 'SUMMARY_UPDATE_SUCCESS',
    SUMMARY_UPDATE_REQUEST = 'SUMMARY_UPDATE_REQUEST',
    SUMMARY_UPDATE_FAILURE = 'SUMMARY_UPDATE_FAILURE',
}
