/* eslint-disable no-shadow */

export enum TotalTypes {
    TOTAL_CREATE_SUCCESS = 'TOTAL_CREATE_SUCCESS',
    TOTAL_CREATE_REQUEST = 'TOTAL_CREATE_REQUEST',
    TOTAL_CREATE_FAILURE = 'TOTAL_CREATE_FAILURE',
    TOTAL_UPDATE_SUCCESS = 'TOTAL_UPDATE_SUCCESS',
    TOTAL_UPDATE_REQUEST = 'TOTAL_UPDATE_REQUEST',
    TOTAL_UPDATE_FAILURE = 'TOTAL_UPDATE_FAILURE',
    TOTAL_REMOVE_SUCCESS = 'TOTAL_REMOVE_SUCCESS',
    TOTAL_REMOVE_REQUEST = 'TOTAL_REMOVE_REQUEST',
    TOTAL_REMOVE_FAILURE = 'TOTAL_REMOVE_FAILURE',
}
